### ISSUE TITLE
Admissions system v1

### ISSUE THREAD

**Issue by rukmal** [avinyafoundation/admissions#1]
This ticket covers the implementation of the Admissions system for the Avinya Foundation.

- [x] Avinya-Foundation/admissions#2
- [x] Avinya-Foundation/admissions#4
- [x] Avinya-Foundation/admissions#5
- [x] Avinya-Foundation/admissions-application-frontend#1
- [x] Avinya-Foundation/admissions-application-frontend#2
- [x] Avinya-Foundation/global-data#23
- [x] Avinya-Foundation/global-data#24
- [x] Avinya-Foundation/global-data#25
- [x] Avinya-Foundation/global-data#26
- [x] #13
- [x] #14
- [x] Avinya-Foundation/admissions-application-frontend#3
- [x] Avinya-Foundation/admissions-application-frontend#4
- [x] #15
- [ ] Pick the location from the map 
- [ ] Record / upload vide of reading an essay 
- [x] #16
